### ISSUE TITLE
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

### ISSUE THREAD

**Issue by archer920** [heroku/heroku-buildpack-xvfb-google-chrome#13]
Hi! I'm getting this startup exception when I do a deploy on Heroku. I'm hoping someone can help me with it.

```
2018-07-26T17:01:00.929284+00:00 app[web.1]: org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
2018-07-26T17:01:00.929285+00:00 app[web.1]: Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
2018-07-26T17:01:00.929287+00:00 app[web.1]: System info: host: 'ebd033c4-4bf1-41cd-8ce7-4d345aa7e6e2', ip: '172.17.207.246', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-1019-aws', java.version: '1.8.0_171-heroku'
2018-07-26T17:01:00.929289+00:00 app[web.1]: Driver info: driver.version: ChromeDriver
2018-07-26T17:01:00.929291+00:00 app[web.1]: at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622) ~[selenium-remote-driver-3.9.1.jar!/:na]
2018-07-26T17:01:00.929292+00:00 app[web.1]: at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219) ~[selenium-remote-driver-3.9.1.jar!/:na]
2018-07-26T17:01:00.929304+00:00 app[web.1]: at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142) ~[selenium-remote-driver-3.9.1.jar!/:na]
2018-07-26T17:01:00.929305+00:00 app[web.1]: at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181) ~[selenium-chrome-driver-3.9.1.jar!/:na]
2018-07-26T17:01:00.929307+00:00 app[web.1]: at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168) ~[selenium-chrome-driver-3.9.1.jar!/:na]
2018-07-26T17:01:00.929308+00:00 app[web.1]: at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157) ~[selenium-chrome-driver-3.9.1.jar!/:na]
2018-07-26T17:01:00.929310+00:00 app[web.1]: at com.stonesoupprogramming.automotivecms.cmsbackend.selenium.AbstractScrapeInstance.create(WebScraping.kt:27) ~[classes!/:0.0.1-SNAPSHOT]
2018-07-26T17:01:00.929312+00:00 app[web.1]: at com.stonesoupprogramming.automotivecms.cmsbackend.service.BaseScrapeService.runScrape(ScrapeService.kt:26) ~[classes!/:0.0.1-SNAPSHOT]
2018-07-26T17:01:00.929314+00:00 app[web.1]: at com.stonesoupprogramming.automotivecms.cmsbackend.service.BaseScrapeService$$FastClassBySpringCGLIB$$cc359a12.invoke(<generated>) [classes!/:0.0.1-SNAPSHOT]
2018-07-26T17:01:00.929315+00:00 app[web.1]: at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-07-26T17:01:00.929317+00:00 app[web.1]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) [spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-07-26T17:01:00.929319+00:00 app[web.1]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-07-26T17:01:00.929321+00:00 app[web.1]: at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) [spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-07-26T17:01:00.929322+00:00 app[web.1]: at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171-heroku]
2018-07-26T17:01:00.929324+00:00 app[web.1]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171-heroku]
2018-07-26T17:01:00.929326+00:00 app[web.1]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171-heroku]
2018-07-26T17:01:00.929327+00:00 app[web.1]: at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171-heroku]
```

This is the code that I am using to launch the selenium instance. 
```
          with((ChromeOptions())){
                logger.info("Chrome binary at: ${System.getenv("GOOGLE_CHROME_BIN")}")
                setHeadless(true)
                setBinary(System.getenv("GOOGLE_CHROME_BIN"))
                addArguments(listOf("--disable-dev-shm-usage", "--no-sandbox", "--disable-gpu --remote-debugging-port=9222"))
                this@AbstractScrapeInstance.driver = ChromeDriver(this@with)
            }
```

I also tried with with the GOOGLE_CHROME_SHIM variable but that doesn't seem to make a difference. My code is Kotlin running on Spring Boot 2. Thanks for the help!

**Comment by archer920** [comment]
Issue was caused by a bug in the application
