### ISSUE TITLE
Using SHIM cant find chrome binary and BIN causes ReadTimeout upon instantiating WebDriver

### ISSUE THREAD

**Issue by arinhouck** [heroku/heroku-buildpack-xvfb-google-chrome#8]
```
Selenium::WebDriver::Error::UnknownError: unknown error: no chrome binary at /tmp/build_ebdd71b82c2dd665242b0a925b088ada/.apt/usr/bin/google-chrome-stable
  (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57),platform=Linux 3.13.0-123-generic x86_64)
        from lib/scrap.rb:14:in `run'
        from (irb):2
```

If I use GOOGLE_CHROME_BIN it will work but immediately will fail when instantiating driver (line 14 below)
```
Net::ReadTimeout: Net::ReadTimeout
        from lib/scrap.rb:14:in `run'
        from (irb):2
```
```
driver = Selenium::WebDriver.for :chrome, desired_capabilities: Selenium::WebDriver::Remote::Capabilities.chrome(chrome_opts)
```

I had my script working on heroku with headless previously but now changing to xvfb as the headless version was losing connection half way through script when going through a page with infinite scroll.

Script runs fine locally in non-headless mode.

**Comment by zharikovpro** [comment]
May be related with #5.
